# Generated by Django 4.0.3 on 2022-04-16 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='desc',
        ),
    ]
