# Generated by Django 4.0.4 on 2022-04-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_submission_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='template',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
