# Generated by Django 4.0.4 on 2022-04-29 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_problem_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='template',
        ),
    ]
